# Generated by Django 5.2.1 on 2025-06-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_fooditem_description_alter_fooditem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
