# Generated by Django 5.2.1 on 2025-06-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_fooditem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
